name: Skyblock Slayers
version: ${project.version}
main: com.guccifox.slayers.Slayers
api-version: 1.14
authors: [ Gucci Fox ]
description: Skyblock slayers remake from Hypixel
website: guccifoxdev.xyz
commands:
  slayer:
  spawnboss:
  batphone:
  unbreakable:
